name: Tests

on:
  push:
    paths-ignore:
      - '*.md'
      - LICENSE
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Lint
        run: uvx ruff check

  integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start Gancio
        run: >-
          docker run -d
          --name gancio
          --restart unless-stopped
          -e NODE_ENV=development
          -p 13120:13120
          cisti/gancio

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync --extra test

      - name: Run tests
        run: uv run pytest -m integration -v --cov --cov-report=term-missing